version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@2.1.0

jobs:

  run-trunk-tests:
    parameters:
      database:
        type: enum
        enum: ['mysql', 'pg', 'mariadb', 'sqlite3']
    executor:
      name: redmine-plugin/ruby-<< parameters.database >>
      ruby_version: '3.0'
    steps:
      - checkout
      - redmine-plugin/download-redmine-trunk
      # Prevent Restore failure due to lack of Gemfile.local
      - run:
          working_directory: 'redmine'
          command: touch Gemfile.local
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/test

  run-tests:
    parameters:
      redmine_version:
        type: string
      ruby_version:
        type: string
      database:
        type: enum
        enum: ['mysql', 'pg', 'mariadb', 'sqlite3']
    executor:
      name: redmine-plugin/ruby-<< parameters.database >>
      ruby_version: << parameters.ruby_version >>
    steps:
      - checkout
      - redmine-plugin/download-redmine:
          version: << parameters.redmine_version >>
      # Prevent Restore failure due to lack of Gemfile.local
      - run:
          working_directory: 'redmine'
          command: touch Gemfile.local
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/test

  run-old-redmine-tests:
    parameters:
      redmine_version:
        type: string
      ruby_version:
        type: string
      database:
        type: enum
        enum: ['mysql', 'pg', 'mariadb', 'sqlite3']
    executor:
      name: redmine-plugin/ruby-<< parameters.database >>
      ruby_version: << parameters.ruby_version >>
      # Postgresql10 is not available prior to Rails 5.0.
      db_version: '9.6'
    steps:
      - checkout
      - redmine-plugin/download-redmine:
          version: << parameters.redmine_version >>
      # Prevent Restore failure due to lack of Gemfile.local
      - run:
          working_directory: 'redmine'
          command: touch Gemfile.local
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/test

workflows:
  version: 2
  test:
    jobs:
      - run-trunk-tests:
          database: 'pg'
      - run-trunk-tests:
          database: 'mysql'
      - run-trunk-tests:
          database: 'mariadb'
      - run-trunk-tests:
          database: 'sqlite3'

      - run-tests:
          redmine_version: '4.2.1'
          ruby_version: '2.7'
          database: 'pg'
      - run-tests:
          redmine_version: '4.2.1'
          ruby_version: '2.7'
          database: 'mysql'
      - run-tests:
          redmine_version: '4.2.1'
          ruby_version: '2.7'
          database: 'mariadb'
      - run-tests:
          redmine_version: '4.2.1'
          ruby_version: '2.7'
          database: 'sqlite3'
      - run-tests:
          redmine_version: '4.1.3'
          ruby_version: '2.6'
          database: 'pg'
      - run-tests:
          redmine_version: '4.1.3'
          ruby_version: '2.6'
          database: 'mysql'
      - run-tests:
          redmine_version: '4.1.3'
          ruby_version: '2.6'
          database: 'mariadb'
      - run-tests:
          redmine_version: '4.1.3'
          ruby_version: '2.6'
          database: 'sqlite3'
      - run-tests:
          redmine_version: '4.0.9'
          ruby_version: '2.6'
          database: 'pg'
      - run-tests:
          redmine_version: '4.0.9'
          ruby_version: '2.6'
          database: 'mysql'
      - run-tests:
          redmine_version: '4.0.9'
          ruby_version: '2.6'
          database: 'mariadb'
      - run-tests:
          redmine_version: '4.0.9'
          ruby_version: '2.6'
          database: 'sqlite3'

      # Older versions of Redmine only test PostgreSQL.(This is to shorten the execution time.)
      - run-old-redmine-tests:
          redmine_version: '3.4.13'
          ruby_version: '2.4'
          database: 'pg'
      - run-old-redmine-tests:
          redmine_version: '3.3.10'
          ruby_version: '2.3'
          database: 'pg'
